training_params:
  lr: 0.001
  epochs: 40
  batch_size: 2
  voxel_size: [0.2, 0.2, 0.2] #x, y, z
  max_num_points: 10
  max_voxels: 50000
  input_size: 23 #xyz + num classes
  num_classes: 10
  pc_range: [-80, 80, -80, 80, -4, 3] #xmin, xmax, ymin, ymax, zmin, zmax
  sparse_shape: [800, 500, 35]

sequences:
  train: ['035', '052', '105', '030', '113', '002', '084', '028', '119', '044', '005', '102', '034', '077', '064', '067', '058', '019', '015', '037', '095', '120', '066', '023', '071', '117', '098', '139', '038', '116', '046', '088', '089', '040', '033', '016', '024', '122', '039', '158', '069', '124', '123', '106'] # ~60% of the sequences, randomly chosen
  val: ['097', '073', '043', '003', '101', '027', '056', '011', '078', '080', '109', '042', '021', '094', '057'] # ~20% of the sequences, randomly chosen
  test: ['074', '004', '086', '068', '008', '001', '110', '053', '115', '054', '065', '017', '103', '072', '013', '029', '090', '112', '149', '070', '032'] # ~20% of the sequences, randomly chosen

paths:
  source: 'datasets/pandaset/data/data'
  sem2d: 'datasets/pandaset/sem2d'
  sem3d: 'datasets/pandaset/sem3d'
  data_train: 'datasets/pandaset/out/pandaset_infos_train.pkl'
  data_val: 'datasets/pandaset/out/pandaset_infos_val.pkl'

classes: ['Car', 'Motorcycle', 'Truck', 'Pedestrian', 'Road', 'Sidewalk', 'Building', 'Vegetation', 'Signs']

gt_map:
  0: 0
  1: 0
  2: 0
  3: 0
  4: 0
  5: 8 # Vegetation
  6: 0
  7: 5 # Road
  8: 0
  9: 0
  10: 0
  11: 6 # Sidewalk
  12: 0
  13: 1 # Car
  14: 3 # Truck
  15: 3 # Truck
  16: 3 # Truck
  17: 3 # Truck
  18: 2 # Motorcycle
  19: 0
  20: 0
  21: 0
  22: 0
  23: 0
  24: 0
  25: 0
  26: 2 # Bicycle
  27: 0
  28: 0
  29: 0
  30: 4 # Pedestrian
  31: 0
  32: 0
  33: 0
  34: 0
  35: 0
  36: 9 # Signs
  37: 0
  38: 0
  39: 0
  40: 0
  41: 7 # Building
  42: 0

sem_map:
  0: 0
  1: 1 # Car
  2: 2 # Motorcycle
  3: 2 # Motorcycle
  4: 3 # Truck
  5: 0
  6: 4 # Pedestrian
  7: 5 # Road
  8: 6 # Sidewalk
  9: 7 # Building
  10: 0
  11: 8 # Vegetation
  12: 0
  13: 9 # Signs
