training_params:
  lr: 0.001
  epochs: 50
  batch_size: 10
  voxel_size: 0.5
  max_num_points: 20
  max_voxels: 60000
  input_size: 71 #xyz + num classes
  num_classes: 34

sequences:
  train: ['035', '052', '105', '030', '113', '002', '084', '028', '119', '044', '005', '102', '034', '077', '064', '067', '058', '019', '015', '037', '095', '120', '066', '023', '071', '117', '098', '139', '038', '116', '046', '088', '089', '040', '033', '016', '024', '122', '039', '158', '069', '124', '123', '106'] # ~60% of the sequences, randomly chosen
  val: ['097', '073', '043', '003', '101', '027', '056', '011', '078', '080', '109', '042', '021', '094', '057'] # ~20% of the sequences, randomly chosen
  test: ['074', '004', '086', '068', '008', '001', '110', '053', '115', '054', '065', '017', '103', '072', '013', '029', '090', '112', '149', '070', '032'] # ~20% of the sequences, randomly chosen

paths:
  source: 'datasets/pandaset/data/data'
  sem2d: 'datasets/pandaset/sem2d'
  sem3d: 'datasets/pandaset/sem3d'
  data_train: 'datasets/pandaset/out/pandaset_infos_train.pkl'
  data_val: 'datasets/pandaset/out/pandaset_infos_val.pkl'
