training_params:
  name: 'pandaset'
  lr: 0.001
  epochs: 15
  batch_size: 1
  voxel_size: [0.2, 0.2, 0.2] #x, y, z
  max_num_points: 10
  max_voxels: 30000
  input_size: 23 #xyz + num classes
  num_classes: 10
  unified_mask: False
  pc_range: [-80, 80, -80, 80, -4, 3] #xmin, xmax, ymin, ymax, zmin, zmax
  sparse_shape: [800, 500, 35]
  val_rate: 1 #epochs
  offline_loader: False
  train_metrics: False # Whether to upload train iou, loss and acc metrics to tb

sequences:
  train: ['035', '052', '105', '030', '113', '002', '084', '028', '119', '044', '005', '102', '034', '077', '064', '067', '058', '019', '015', '037', '095', '120', '066', '023', '071', '117', '098', '139', '038', '116', '046', '088', '089', '040', '033', '016', '024', '122', '039', '158', '069', '124', '123', '106'] # ~60% of the sequences, randomly chosen
  val: ['097', '073', '043', '003', '101', '027', '056', '011', '078', '080', '109', '042', '021', '094', '057'] # ~20% of the sequences, randomly chosen
  test: ['074', '004', '086', '068', '008', '001', '110', '053', '115', '054', '065', '017', '103', '072', '013', '029', '090', '112', '149', '070', '032'] # ~20% of the sequences, randomly chosen

paths:
  source: 'datasets/pandaset/data/data'
  sem_images: 'datasets/pandaset/semantic_images'
  sem2d: 'datasets/pandaset/sem2d'
  sem2d_scores: 'datasets/pandaset/sem2d_scores'
  sem3d: 'datasets/pandaset/sem3d'
  pickle: 'datasets/pandaset/offline_data'
  data_train: 'datasets/pandaset/out/pandaset_infos_train.pkl'
  data_val: 'datasets/pandaset/out/pandaset_infos_val.pkl'
  model_path: 'out/pandaset/models/test/model-save.pt'

classes: ['Car', 'Motorcycle', 'Truck', 'Pedestrian', 'Road', 'Sidewalk', 'Building', 'Vegetation', 'Signs']
cams: ['front_camera', 'front_left_camera', 'front_right_camera', 'back_camera', 'left_camera', 'right_camera']

gt_map:
  0: 0
  1: 0
  2: 0
  3: 0
  4: 0
  5: 8 # Vegetation
  6: 0
  7: 5 # Road
  8: 0
  9: 0
  10: 0
  11: 6 # Sidewalk
  12: 0
  13: 1 # Car
  14: 3 # Truck
  15: 3 # Truck
  16: 3 # Truck
  17: 3 # Truck
  18: 2 # Motorcycle
  19: 0
  20: 0
  21: 0
  22: 0
  23: 0
  24: 0
  25: 0
  26: 2 # Bicycle
  27: 0
  28: 0
  29: 0
  30: 4 # Pedestrian
  31: 0
  32: 0
  33: 0
  34: 0
  35: 0
  36: 9 # Signs
  37: 0
  38: 0
  39: 0
  40: 0
  41: 7 # Building
  42: 0

sem_map:
  0: 0
  1: 1 # Car
  2: 2 # Motorcycle
  3: 3 # Truck
  4: 4 # Pedestrian
  5: 5 # Road
  6: 6 # Sidewalk
  7: 7 # Building
  8: 8 # Vegetation
  9: 0
  10: 9 # Signs

color_map:
  '[0,0,0]': 0
  '[255,0,0]': 1 # Car
  '[182,89,6]': 2 # Bicycle/Motorcycle
  '[255,128,0]': 3 # Truck
  '[0,255,0]': 0 # Small vehicle -> other vehicle?
  '[204,153,255]': 4 # Pedestrian
  '[255,0,255]': 5 # Road
  '[180,150,200]': 6 # Sidewalk
  '[241,230,255]': 7 # Buildings
  '[185,122,87]': 0 # Road blocks -> road barriers?
  '[147,253,194]': 8 # Nature
  '[139,99,108]': 0 # non-drivable street -> ground?
  '[0,255,255]': 9 # Traffic signs -> signs
  '[255,246,143]': 9 # Poles -> signs
  '[0,128,255]': 9 # Traffic signal (moving/blinking signs) -> signs
